Adding post reading duration.
writingink/wink pull request #339
Opened 2021-11-22 15:11 UTC by salah21500

In most popular publishing platforms like Hashnode, Medium or Dev.io every single post has an estimated time for reading this post, So the user will know the time needed to finish the post.

2021-12-02 09:29 UTC, lukeraymonddowning requested changes

2021-12-02 09:29 UTC, lukeraymonddowning commented on src/Http/Controllers/PostsController.php
> +    public function readingDuration(...$text)
Think this would be better placed on the `WinkPost` model

2021-12-02 09:29 UTC, lukeraymonddowning commented on src/Migrations/2018_10_30_000000_create_tables.php
> +            $table->integer('duration');
Doesn't seem that this is used...

2021-12-23 21:38 UTC, salah-jr commented
Thanks @lukeraymonddowning for your time, I'll take that into consideration in my future PR, but, I noticed that this feature is already PRed before many times #204 #114 .

2021-12-23 21:38 UTC, closed without merging